// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// em
List em(NumericMatrix mean_k, NumericVector y, arma::mat squared_error, NumericVector priors, NumericVector weights, double sigma, int maxiter);
RcppExport SEXP DynamicBmaNormalCpp_em(SEXP mean_kSEXP, SEXP ySEXP, SEXP squared_errorSEXP, SEXP priorsSEXP, SEXP weightsSEXP, SEXP sigmaSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mean_k(mean_kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type squared_error(squared_errorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(em(mean_k, y, squared_error, priors, weights, sigma, maxiter));
    return rcpp_result_gen;
END_RCPP
}
