# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The E-M algorithm for Dynamic BMA
#'
#' For the E-M Algorithm for the Dynamic BMA of Rafterey et al.
#' (2005) using the normal distribution. This function will conduct
#' the EM algorithm for maximaziation of the of the
#' Likelihood function as on p. 1159 of Raftery et al. (2005)
#'
#' @title The em algorithm for dynamic bma using the normal distribuiton
#' @param mean_k (NumericMatrix) the bias corrected mean of the forecast
#' for each member of the ensemble (columns) for each
#' time period (rows)
#' @param y (NumericVector) the quantity to be forecast
#' @param squared_error (arma::mat) A matrix with the squared errors for each
#' member of the ensemble (columns) and each time period (rows)
#' @param priors (NumericVector) the prior distribution for the weights (chosen
#' by the user)
#' @param weights (NumericVector) the initial weights to use in the algorithm
#' @param sigma (double) the intial standard deviation for the normal distribution
#' @param maxiter (int) the maximum number of iterations. Defaults to 1000
#' @return A \code{List} with the following elements: \code{weights}, \code{sigma}, and
#' the \code{log_lik}
#' @author Chandler Lutz
#'
em <- function(mean_k, y, squared_error, priors, weights, sigma, maxiter = 1000L) {
    .Call('DynamicBmaNormalCpp_em', PACKAGE = 'DynamicBmaNormalCpp', mean_k, y, squared_error, priors, weights, sigma, maxiter)
}

